### ISSUE TITLE
google_fonts: ^2.0.0 incompatibility in new projects

### ISSUE THREAD

**Issue by benskelton** [HandCash/handcash_connect_sdk_flutter#6]
New flutter 2 projects will use google_fonts ^2.0.0 which apparently is incompatible and produces this error:

flutter --no-color pub get
Running "flutter pub get" in projectname_flutter...         

Because no versions of google_fonts match >2.0.0 <3.0.0 and google_fonts 2.0.0 depends on http ^0.13.0, google_fonts ^2.0.0 requires http ^0.13.0.
And because every version of handcash_connect_sdk depends on http ^0.12.2, google_fonts ^2.0.0 is incompatible with handcash_connect_sdk.
So, because genuineretweets_flutter depends on both handcash_connect_sdk any and google_fonts ^2.0.0, version solving failed.
pub get failed (1; So, because genuineretweets_flutter depends on both handcash_connect_sdk any and google_fonts ^2.0.0, version solving failed.)
Process finished with exit code 1

**Comment by alfredo-handcash** [comment]
Hi! Thanks for open this issue. I think with new version: 0.1.3-dev the dependencies are up to date so this error will be removed. Feel free to open another issue if the problem is not solved!
